version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      - DOCKER=true
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_NAME=postgres
      - JWT_SECRET=secret
      - CORS_ORIGIN=http://localhost:65060
      - CLIENT_ID=131b8243dedb4e09ab117077d813f760
      - CLIENT_SECRET=d0cc5d2647b54940bc8814675b9460b9
      - FRONTEND_URL=http://localhost:4200
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data: